#!/bin/bash
#PBS -N test_tracer
#PBS -j oe
#PBS -l walltime=01:00:00
#PBS -J 0-3
#PBS -r y

echo " --------------------------------------"
echo " Starting ... at YYYY MM DD HH MM SS ="
dt=$(date '+%Y %m %d %H %M %S');
echo "                 $dt"
echo " Program test_tracer"
echo " --------------------------------------"

# Give execution rights for tests scripts
chmod +x getline.sh
chmod +x test_run.sh
chmod +x test_cleanup.sh

# Determine the number of nodes, processors per node, and steps from inputs.txt, up to ppn
nodeslist=( $(cat ${PBS_NODEFILE} | sort | uniq | cut -d'.' -f1) )
nnodes=$(cat ${PBS_NODEFILE} | sort | uniq | wc -l)
nranks=$(cat ${PBS_NODEFILE} | sort | wc -l)
nsteps=$(cat inputs.txt | grep -v '#' | wc -l )
nranks_per_node=$((${nranks} / ${nnodes}))
start_idx=$(( ${PBS_ARRAY_INDEX} * ${nranks_per_node} ))
stop_idx=$(( ${start_idx} + ${nranks_per_node} - 1 ))
echo "nsteps: ${nsteps}, array index: ${PBS_ARRAY_INDEX}"
echo "start_idx=${start_idx} stop_idx=${stop_idx}"

# Make a temporary work directory for array iteration
cd ../../models/lorenz_96_tracer_advection/
rm -r work_test_${PBS_ARRAY_INDEX}
cp -r work work_test_${PBS_ARRAY_INDEX}
cd work_test_${PBS_ARRAY_INDEX}

# Iterate over each test to run from inputs.txt
for step in $(seq ${start_idx} ${stop_idx}); do
    # The last PBS_ARRAY_INDEX could go past nsteps if inputs.txt isn't evenly divisible by ppn
    [ ${step} -ge ${nsteps} ] && break
    # Get the command line arguments from inputs.txt for step (step counter is 0 based, so add 1)
    cmdargs=$( ./../../../developer_tests/tracer_filter/getline.sh ./../../../developer_tests/tracer_filter/inputs.txt $(( ${step} + 1)) )
    echo " PBS_ARRAY_INDEX = ${PBS_ARRAY_INDEX} launching step ${step} / args= ${cmdargs}"
    # Run test script with correct parameters (setup included)
    ./../../../developer_tests/tracer_filter/test_run.sh ${cmdargs}
done

# Wait for all the background processes to complete so PBS doesn't kill them early.
wait

# Job array is done, so it will create a file in the test directory to report that.
touch ./../../../developer_tests/tracer_filter/test_array_finished_${PBS_ARRAY_INDEX}
echo " --------------------------------------"
echo " Array ${PBS_ARRAY_INDEX} finished."

# test_cleanup.sh only cleans up once, but only on the last running array.
cd ~/DART/
./developer_tests/tracer_filter/test_cleanup.sh $(( ${PBS_ARRAY_INDEX} + 1))

echo " Result of tests located in test_result"
echo " once all test arrays finish."
echo " --------------------------------------"
echo ""
echo " --------------------------------------"
echo " Finished ... at YYYY MM DD HH MM SS ="
dt=$(date '+%Y %m %d %H %M %S');
echo "                 $dt"
echo " --------------------------------------"
