#!/bin/bash
#PBS -N test_tracer
#PBS -j oe
#PBS -l walltime=00:10:00
#PBS -r y

echo " --------------------------------------"
echo " Starting ... at YYYY MM DD HH MM SS ="
dt=$(date '+%Y %m %d %H %M %S');
echo "                 $dt"
echo " Program test_solo"
echo " --------------------------------------"

# Extract arguments (v# = argument for test)
# v1 = CSV File, v2 = Ensemble Size, v3 = PE Count (or 0 for new CVS file setup), 
# v4 = positive_tracer, v5 = bounded_above, v6 = post_inf_flavor, v7 = compiler.
echo "$(args)" | read v1 v2 v3 v4 v5 v6 v7

# Set up test and make a temporary work directory
bash test_setup.sh $v7
cd ../../models/lorenz_96_tracer_advection/
rm -r work_test
cp -r work work_test
cd work_test

# Prepare test, then run the individual test
chmod +x ../../../developer_tests/tracer_filter/test_run.sh
./../../../developer_tests/tracer_filter/test_run.sh $v1 $v2 0 $v4 $v5 $v6
./../../../developer_tests/tracer_filter/test_run.sh $v1 $v2 $v3 $v4 $v5 $v6

echo " --------------------------------------"
echo " Test array finished."
echo " Outputting test results:"
echo " --------------------------------------"

# Move out of work_test and output result
cd ..
cat /work_test/temp_test_output
rm -r /work_test

echo " --------------------------------------"
echo " Finished ... at YYYY MM DD HH MM SS ="
dt=$(date '+%Y %m %d %H %M %S');
echo "                 $dt"
echo " --------------------------------------"